#!/bin/bash

###############################################################################
# Vlocity Component Documentation Orchestrator
#
# Usage:
#   ./scripts/document_vlocity_component.sh <component_name> <vlocity_dir> [output_dir]
#
# Example:
#   ./scripts/document_vlocity_component.sh sales_createOrderAPI ./vlocity ./component_docs
#
# This script orchestrates the full Vlocity documentation workflow:
#   1. Ensure dependency index exists
#   2. Run impact analysis
#   3. Run architecture mapping
#   4. Run datapack review
#   5. Synthesize results
###############################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Arguments
COMPONENT_NAME="${1:-}"
VLOCITY_DIR="${2:-}"
OUTPUT_DIR="${3:-.}"

# Validate arguments
if [ -z "$COMPONENT_NAME" ] || [ -z "$VLOCITY_DIR" ]; then
    echo -e "${RED}Usage: $0 <component_name> <vlocity_dir> [output_dir]${NC}"
    echo ""
    echo "Example:"
    echo "  $0 sales_createOrderAPI ./vlocity ./component_docs"
    exit 1
fi

# Validate vlocity directory exists
if [ ! -d "$VLOCITY_DIR" ]; then
    echo -e "${RED}Error: Vlocity directory not found: $VLOCITY_DIR${NC}"
    exit 1
fi

# Create output directory
mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR="$(cd "$OUTPUT_DIR" && pwd)"

# Resolve script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Find vlocity-dependency-indexer script
INDEXER_SCRIPT="$PROJECT_ROOT/skills/vlocity-dependency-indexer/scripts/build_index.py"
if [ ! -f "$INDEXER_SCRIPT" ]; then
    echo -e "${RED}Error: vlocity-dependency-indexer script not found at $INDEXER_SCRIPT${NC}"
    exit 1
fi

# Normalize paths
VLOCITY_DIR="$(cd "$VLOCITY_DIR" && pwd)"
VLOCITY_PARENT="$(dirname "$VLOCITY_DIR")"

# Resolve index directory
INDEX_DIR="$VLOCITY_PARENT/dependency-index"
INDEX_FILE="$INDEX_DIR/index.json"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Vlocity Component Documentation${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "Component:  ${YELLOW}$COMPONENT_NAME${NC}"
echo -e "Vlocity:    ${YELLOW}$VLOCITY_DIR${NC}"
echo -e "Output:     ${YELLOW}$OUTPUT_DIR${NC}"
echo ""

# Step 1: Ensure index exists
echo -e "${BLUE}[1/4]${NC} Checking dependency index..."
if [ ! -f "$INDEX_FILE" ]; then
    echo -e "${YELLOW}  → Index not found, generating...${NC}"
    python3 "$INDEXER_SCRIPT" --generate-all "$VLOCITY_DIR" "$VLOCITY_PARENT"
    if [ ! -f "$INDEX_FILE" ]; then
        echo -e "${RED}Error: Failed to generate index${NC}"
        exit 1
    fi
    echo -e "${GREEN}  ✓ Index generated${NC}"
else
    echo -e "${GREEN}  ✓ Index found${NC}"
fi
echo ""

# Step 2: Verify journey document was created
echo -e "${BLUE}[2/4]${NC} Verifying generated documentation..."
JOURNEY_FILE="$INDEX_DIR/journeys/${COMPONENT_NAME}-journey.md"
FLOW_FILE="$INDEX_DIR/flows/${COMPONENT_NAME}-flow.md"

if [ ! -f "$JOURNEY_FILE" ]; then
    echo -e "${RED}Error: Journey document not found: $JOURNEY_FILE${NC}"
    exit 1
fi
echo -e "${GREEN}  ✓ Journey document: $JOURNEY_FILE${NC}"

if [ -f "$FLOW_FILE" ]; then
    echo -e "${GREEN}  ✓ Flow diagram: $FLOW_FILE${NC}"
else
    echo -e "${YELLOW}  ⚠ Flow diagram not found (component may not be Integration Procedure)${NC}"
fi
echo ""

# Step 3: Copy results to output directory
echo -e "${BLUE}[3/4]${NC} Gathering documentation..."
cp "$JOURNEY_FILE" "$OUTPUT_DIR/${COMPONENT_NAME}-journey.md"
if [ -f "$FLOW_FILE" ]; then
    cp "$FLOW_FILE" "$OUTPUT_DIR/${COMPONENT_NAME}-flow.md"
fi

# Copy analysis bundle if it exists
BUNDLE_FILE="$INDEX_DIR/${COMPONENT_NAME}-analysis-bundle.json"
if [ -f "$BUNDLE_FILE" ]; then
    cp "$BUNDLE_FILE" "$OUTPUT_DIR/${COMPONENT_NAME}-analysis-bundle.json"
    echo -e "${GREEN}  ✓ Copied analysis bundle${NC}"
fi

echo -e "${GREEN}  ✓ Documentation gathered${NC}"
echo ""

# Step 4: Generate summary report
echo -e "${BLUE}[4/4]${NC} Generating summary report..."

REPORT_FILE="$OUTPUT_DIR/DOCUMENTATION_SUMMARY.md"
cat > "$REPORT_FILE" << 'EOF'
# Vlocity Component Documentation Summary

Generated by: `document_vlocity_component.sh`

## Files Generated

### Journey Document
The architecture diagram and complete dependency table for this component.
EOF

cat >> "$REPORT_FILE" << EOF

**Location:** \`${COMPONENT_NAME}-journey.md\`

EOF

if [ -f "$OUTPUT_DIR/${COMPONENT_NAME}-flow.md" ]; then
    cat >> "$REPORT_FILE" << EOF
### Flow Diagram
The component execution flow showing called components in sequence.

**Location:** \`${COMPONENT_NAME}-flow.md\`

EOF
fi

cat >> "$REPORT_FILE" << EOF
## Next Steps

### For Impact Analysis
Review the journey document's "All Dependencies" section to understand:
- **Upstream Impact:** Components that call this one (what breaks if you change it)
- **Downstream Impact:** Components this one depends on (what to retest)
- **Risk Level:** HIGH/MEDIUM/LOW based on caller count

### For Architecture Review
- Check the Mermaid diagram in the journey document
- Identify integration points with DataRaptors, REST endpoints, Remote Actions
- Look for hidden dependencies (preTransformBundle, postTransformBundle on DataRaptors)

### For Code Review
Consider using \`vlocity-datapack-reviewer\` to scan for:
- Hardcoded Salesforce IDs
- Missing error handling
- Performance bottlenecks
- Complex conditional logic

### For Testing
Based on the upstream callers identified in the journey:
- Create test cases for each direct caller
- Plan regression testing for all transitive callers
- Validate data flow through the dependency chain

## Analysis Bundle

An JSON analysis bundle is available with machine-readable metadata:

\`\`\`json
{
  "primary_element": "${COMPONENT_NAME}",
  "total_dependencies": <count>,
  "dependency_list": [...],
  "generated_artifacts": [...]
}
\`\`\`

This can be consumed by other tools for further analysis.

---

**Generated:** $(date)
**Component:** ${COMPONENT_NAME}
**Vlocity Directory:** ${VLOCITY_DIR}

EOF

echo -e "${GREEN}  ✓ Summary report created: DOCUMENTATION_SUMMARY.md${NC}"
echo ""

# Final summary
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}✓ Documentation Complete${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Output files:"
echo -e "  ${YELLOW}${OUTPUT_DIR}/${COMPONENT_NAME}-journey.md${NC}"
if [ -f "$OUTPUT_DIR/${COMPONENT_NAME}-flow.md" ]; then
    echo -e "  ${YELLOW}${OUTPUT_DIR}/${COMPONENT_NAME}-flow.md${NC}"
fi
echo -e "  ${YELLOW}${OUTPUT_DIR}/DOCUMENTATION_SUMMARY.md${NC}"
if [ -f "$OUTPUT_DIR/${COMPONENT_NAME}-analysis-bundle.json" ]; then
    echo -e "  ${YELLOW}${OUTPUT_DIR}/${COMPONENT_NAME}-analysis-bundle.json${NC}"
fi
echo ""
echo "Next: Review the journey document for impact analysis and architecture overview."
